<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AssemblyName>Jellyfin.Plugin.Reelay.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Plugin.Reelay\Jellyfin.Plugin.Reelay.csproj" />
    <EmbeddedResource Include="..\Jellyfin.Plugin.Reelay\Configuration\configPage.html" Link="Configuration\configPage.html" LogicalName="Jellyfin.Plugin.Reelay.Tests.Configuration.configPage.html" />
  </ItemGroup>
</Project>
